#!/usr/bin/env php 
<?php

namespace BrainGames\Games;

use function cli\line;
use function BrainGames\Engine\answerTheQuestion;
use function BrainGames\Engine\askQuestion;
use function BrainGames\Engine\checkAnswer;
use function BrainGames\Engine\createQuestion;
use function BrainGames\Engine\getRandomNumber;
use function BrainGames\Engine\isContinueGame;
use function BrainGames\Helpers\BrainProgressionHelpers\getExcludedNumber;
use function BrainGames\Helpers\BrainProgressionHelpers\getProgression;
use function BrainGames\Helpers\BrainCalcHelpers\calcExpression;
use function BrainGames\Helpers\BrainCalcHelpers\getRandomOperation;
use function BrainGames\Helpers\BrainGCDHelpers\getGCD;
use function BrainGames\Helpers\BrainEvenHelpers\isEven;
use function BrainGames\Helpers\BrainPrimeHelpers\isPrime;

function startBrainProgression(): int
{
    $quantityCorrectAnswers = 0;
    $isCorrectAnswer = true;
    
    do {
        $progressionLength = getRandomNumber(5, 10);
        $increment = getRandomNumber(1, 10);
        $excludedNumberIndex = getRandomNumber(0, $progressionLength - 1);
        $progression = getProgression($progressionLength, $excludedNumberIndex, $increment);
        $expected = getExcludedNumber($progression, $excludedNumberIndex, $increment);

        $progression = createQuestion($progression);
        askQuestion($progression);
        $answer = answerTheQuestion();
        $isCorrectAnswer = checkAnswer($expected, $answer);

        if ($isCorrectAnswer) {
            $quantityCorrectAnswers++;
            line('Correct!');
        } else {
            line("'%s' is wrong answer ;(. Correct answer was '%s'.", $answer, $expected);
        }
    } while (isContinueGame($quantityCorrectAnswers, $isCorrectAnswer));

    return $quantityCorrectAnswers;
}

function startBrainCalc(): int
{
    $quantityCorrectAnswers = 0;
    $isCorrectAnswer = true;
    
    do {
        $firstOperand = getRandomNumber();
        $operation = getRandomOperation();

        if ($operation === '*') {
            $secondOperand = getRandomNumber(0, 10);
        } else {
            $secondOperand = getRandomNumber();
        }

        $expected = calcExpression($firstOperand, $secondOperand, $operation);

        $expression = createQuestion($firstOperand, $operation, $secondOperand);
        askQuestion($expression);
        $answer = answerTheQuestion();
        $isCorrectAnswer = checkAnswer($expected, $answer);

        if ($isCorrectAnswer) {
            $quantityCorrectAnswers++;
            line('Correct!');
        } else {
            line("'%s' is wrong answer ;(. Correct answer was '%s'.", $answer, $expected);
        }
    } while (isContinueGame($quantityCorrectAnswers, $isCorrectAnswer));

    return $quantityCorrectAnswers;
}

function startBrainEven(): int
{
    $quantityCorrectAnswers = 0;
    $isCorrectAnswer = true;

    do {
        $number = getRandomNumber();
        $expected = isEven($number) ? 'yes' : 'no';

        askQuestion($number);
        $answer = answerTheQuestion();
        $isCorrectAnswer = checkAnswer($expected, $answer);

        if ($isCorrectAnswer) {
            $quantityCorrectAnswers++;
            line('Correct!');
        } else {
            line("'%s' is wrong answer ;(. Correct answer was '%s'.", $answer, $expected);
        }
    } while (isContinueGame($quantityCorrectAnswers, $isCorrectAnswer));

    return $quantityCorrectAnswers;
}

function startBrainPrime(): int
{
    $quantityCorrectAnswers = 0;
    $isCorrectAnswer = true;

    do {
        $number = getRandomNumber(2, 100);
        $expected = isPrime($number) ? 'yes' : 'no';

        askQuestion($number);
        $answer = answerTheQuestion();
        $isCorrectAnswer = checkAnswer($expected, $answer);

        if ($isCorrectAnswer) {
            $quantityCorrectAnswers++;
            line('Correct!');
        } else {
            line("'%s' is wrong answer ;(. Correct answer was '%s'.", $answer, $expected);
        }
    } while (isContinueGame($quantityCorrectAnswers, $isCorrectAnswer));

    return $quantityCorrectAnswers;
}

function startBrainGCD(): int
{
    $quantityCorrectAnswers = 0;
    $isCorrectAnswer = true;

    do {
        $multiplier = getRandomNumber(2, 5);
        $firstNumber = getRandomNumber(1, 50) * $multiplier;
        $secondNumber = getRandomNumber(1, 50) * $multiplier;
        $expected = getGCD($firstNumber, $secondNumber, $multiplier);
        
        $numbersRow = createQuestion($firstNumber, $secondNumber);
        askQuestion($numbersRow);
        $answer = answerTheQuestion();
        $isCorrectAnswer = checkAnswer($expected, $answer);

        if ($isCorrectAnswer) {
            $quantityCorrectAnswers++;
            line('Correct!');
        } else {
            line("'%s' is wrong answer ;(. Correct answer was '%s'.", $answer, $expected);
        }
    } while (isContinueGame($quantityCorrectAnswers, $isCorrectAnswer));

    return $quantityCorrectAnswers;
}
